# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cjrequena/Development/Repositories/github/cjrequena/learning-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cjrequena/Development/Repositories/github/cjrequena/learning-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cjrequena/Development/Repositories/github/cjrequena/learning-cpp/CMakeFiles /Users/cjrequena/Development/Repositories/github/cjrequena/learning-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cjrequena/Development/Repositories/github/cjrequena/learning-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named learning_cpp

# Build rule for target.
learning_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 learning_cpp
.PHONY : learning_cpp

# fast build rule for target.
learning_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/build
.PHONY : learning_cpp/fast

src/0-helloworld/HelloWorld.o: src/0-helloworld/HelloWorld.cpp.o
.PHONY : src/0-helloworld/HelloWorld.o

# target to build an object file
src/0-helloworld/HelloWorld.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/0-helloworld/HelloWorld.cpp.o
.PHONY : src/0-helloworld/HelloWorld.cpp.o

src/0-helloworld/HelloWorld.i: src/0-helloworld/HelloWorld.cpp.i
.PHONY : src/0-helloworld/HelloWorld.i

# target to preprocess a source file
src/0-helloworld/HelloWorld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/0-helloworld/HelloWorld.cpp.i
.PHONY : src/0-helloworld/HelloWorld.cpp.i

src/0-helloworld/HelloWorld.s: src/0-helloworld/HelloWorld.cpp.s
.PHONY : src/0-helloworld/HelloWorld.s

# target to generate assembly for a file
src/0-helloworld/HelloWorld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/0-helloworld/HelloWorld.cpp.s
.PHONY : src/0-helloworld/HelloWorld.cpp.s

src/1-datatypes/DataTypes.o: src/1-datatypes/DataTypes.cpp.o
.PHONY : src/1-datatypes/DataTypes.o

# target to build an object file
src/1-datatypes/DataTypes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/1-datatypes/DataTypes.cpp.o
.PHONY : src/1-datatypes/DataTypes.cpp.o

src/1-datatypes/DataTypes.i: src/1-datatypes/DataTypes.cpp.i
.PHONY : src/1-datatypes/DataTypes.i

# target to preprocess a source file
src/1-datatypes/DataTypes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/1-datatypes/DataTypes.cpp.i
.PHONY : src/1-datatypes/DataTypes.cpp.i

src/1-datatypes/DataTypes.s: src/1-datatypes/DataTypes.cpp.s
.PHONY : src/1-datatypes/DataTypes.s

# target to generate assembly for a file
src/1-datatypes/DataTypes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/1-datatypes/DataTypes.cpp.s
.PHONY : src/1-datatypes/DataTypes.cpp.s

src/2-controlflows/ControlFlows.o: src/2-controlflows/ControlFlows.cpp.o
.PHONY : src/2-controlflows/ControlFlows.o

# target to build an object file
src/2-controlflows/ControlFlows.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/2-controlflows/ControlFlows.cpp.o
.PHONY : src/2-controlflows/ControlFlows.cpp.o

src/2-controlflows/ControlFlows.i: src/2-controlflows/ControlFlows.cpp.i
.PHONY : src/2-controlflows/ControlFlows.i

# target to preprocess a source file
src/2-controlflows/ControlFlows.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/2-controlflows/ControlFlows.cpp.i
.PHONY : src/2-controlflows/ControlFlows.cpp.i

src/2-controlflows/ControlFlows.s: src/2-controlflows/ControlFlows.cpp.s
.PHONY : src/2-controlflows/ControlFlows.s

# target to generate assembly for a file
src/2-controlflows/ControlFlows.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/2-controlflows/ControlFlows.cpp.s
.PHONY : src/2-controlflows/ControlFlows.cpp.s

src/3-functions/Functions.o: src/3-functions/Functions.cpp.o
.PHONY : src/3-functions/Functions.o

# target to build an object file
src/3-functions/Functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/3-functions/Functions.cpp.o
.PHONY : src/3-functions/Functions.cpp.o

src/3-functions/Functions.i: src/3-functions/Functions.cpp.i
.PHONY : src/3-functions/Functions.i

# target to preprocess a source file
src/3-functions/Functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/3-functions/Functions.cpp.i
.PHONY : src/3-functions/Functions.cpp.i

src/3-functions/Functions.s: src/3-functions/Functions.cpp.s
.PHONY : src/3-functions/Functions.s

# target to generate assembly for a file
src/3-functions/Functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/3-functions/Functions.cpp.s
.PHONY : src/3-functions/Functions.cpp.s

src/4-modifiertypes/ModifierTypes.o: src/4-modifiertypes/ModifierTypes.cpp.o
.PHONY : src/4-modifiertypes/ModifierTypes.o

# target to build an object file
src/4-modifiertypes/ModifierTypes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/4-modifiertypes/ModifierTypes.cpp.o
.PHONY : src/4-modifiertypes/ModifierTypes.cpp.o

src/4-modifiertypes/ModifierTypes.i: src/4-modifiertypes/ModifierTypes.cpp.i
.PHONY : src/4-modifiertypes/ModifierTypes.i

# target to preprocess a source file
src/4-modifiertypes/ModifierTypes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/4-modifiertypes/ModifierTypes.cpp.i
.PHONY : src/4-modifiertypes/ModifierTypes.cpp.i

src/4-modifiertypes/ModifierTypes.s: src/4-modifiertypes/ModifierTypes.cpp.s
.PHONY : src/4-modifiertypes/ModifierTypes.s

# target to generate assembly for a file
src/4-modifiertypes/ModifierTypes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/4-modifiertypes/ModifierTypes.cpp.s
.PHONY : src/4-modifiertypes/ModifierTypes.cpp.s

src/5-numbers/Numbers.o: src/5-numbers/Numbers.cpp.o
.PHONY : src/5-numbers/Numbers.o

# target to build an object file
src/5-numbers/Numbers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/5-numbers/Numbers.cpp.o
.PHONY : src/5-numbers/Numbers.cpp.o

src/5-numbers/Numbers.i: src/5-numbers/Numbers.cpp.i
.PHONY : src/5-numbers/Numbers.i

# target to preprocess a source file
src/5-numbers/Numbers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/5-numbers/Numbers.cpp.i
.PHONY : src/5-numbers/Numbers.cpp.i

src/5-numbers/Numbers.s: src/5-numbers/Numbers.cpp.s
.PHONY : src/5-numbers/Numbers.s

# target to generate assembly for a file
src/5-numbers/Numbers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/5-numbers/Numbers.cpp.s
.PHONY : src/5-numbers/Numbers.cpp.s

src/6-arrays/Arrays.o: src/6-arrays/Arrays.cpp.o
.PHONY : src/6-arrays/Arrays.o

# target to build an object file
src/6-arrays/Arrays.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/6-arrays/Arrays.cpp.o
.PHONY : src/6-arrays/Arrays.cpp.o

src/6-arrays/Arrays.i: src/6-arrays/Arrays.cpp.i
.PHONY : src/6-arrays/Arrays.i

# target to preprocess a source file
src/6-arrays/Arrays.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/6-arrays/Arrays.cpp.i
.PHONY : src/6-arrays/Arrays.cpp.i

src/6-arrays/Arrays.s: src/6-arrays/Arrays.cpp.s
.PHONY : src/6-arrays/Arrays.s

# target to generate assembly for a file
src/6-arrays/Arrays.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/6-arrays/Arrays.cpp.s
.PHONY : src/6-arrays/Arrays.cpp.s

src/7-strings/Strings.o: src/7-strings/Strings.cpp.o
.PHONY : src/7-strings/Strings.o

# target to build an object file
src/7-strings/Strings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/7-strings/Strings.cpp.o
.PHONY : src/7-strings/Strings.cpp.o

src/7-strings/Strings.i: src/7-strings/Strings.cpp.i
.PHONY : src/7-strings/Strings.i

# target to preprocess a source file
src/7-strings/Strings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/7-strings/Strings.cpp.i
.PHONY : src/7-strings/Strings.cpp.i

src/7-strings/Strings.s: src/7-strings/Strings.cpp.s
.PHONY : src/7-strings/Strings.s

# target to generate assembly for a file
src/7-strings/Strings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/7-strings/Strings.cpp.s
.PHONY : src/7-strings/Strings.cpp.s

src/8-datetime/DateTime.o: src/8-datetime/DateTime.cpp.o
.PHONY : src/8-datetime/DateTime.o

# target to build an object file
src/8-datetime/DateTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/8-datetime/DateTime.cpp.o
.PHONY : src/8-datetime/DateTime.cpp.o

src/8-datetime/DateTime.i: src/8-datetime/DateTime.cpp.i
.PHONY : src/8-datetime/DateTime.i

# target to preprocess a source file
src/8-datetime/DateTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/8-datetime/DateTime.cpp.i
.PHONY : src/8-datetime/DateTime.cpp.i

src/8-datetime/DateTime.s: src/8-datetime/DateTime.cpp.s
.PHONY : src/8-datetime/DateTime.s

# target to generate assembly for a file
src/8-datetime/DateTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/8-datetime/DateTime.cpp.s
.PHONY : src/8-datetime/DateTime.cpp.s

src/9-operators/Operators.o: src/9-operators/Operators.cpp.o
.PHONY : src/9-operators/Operators.o

# target to build an object file
src/9-operators/Operators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/9-operators/Operators.cpp.o
.PHONY : src/9-operators/Operators.cpp.o

src/9-operators/Operators.i: src/9-operators/Operators.cpp.i
.PHONY : src/9-operators/Operators.i

# target to preprocess a source file
src/9-operators/Operators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/9-operators/Operators.cpp.i
.PHONY : src/9-operators/Operators.cpp.i

src/9-operators/Operators.s: src/9-operators/Operators.cpp.s
.PHONY : src/9-operators/Operators.s

# target to generate assembly for a file
src/9-operators/Operators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/9-operators/Operators.cpp.s
.PHONY : src/9-operators/Operators.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/pointers/Pointers.o: src/pointers/Pointers.cpp.o
.PHONY : src/pointers/Pointers.o

# target to build an object file
src/pointers/Pointers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/pointers/Pointers.cpp.o
.PHONY : src/pointers/Pointers.cpp.o

src/pointers/Pointers.i: src/pointers/Pointers.cpp.i
.PHONY : src/pointers/Pointers.i

# target to preprocess a source file
src/pointers/Pointers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/pointers/Pointers.cpp.i
.PHONY : src/pointers/Pointers.cpp.i

src/pointers/Pointers.s: src/pointers/Pointers.cpp.s
.PHONY : src/pointers/Pointers.s

# target to generate assembly for a file
src/pointers/Pointers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/pointers/Pointers.cpp.s
.PHONY : src/pointers/Pointers.cpp.s

src/storageclasses/StorageClasses.o: src/storageclasses/StorageClasses.cpp.o
.PHONY : src/storageclasses/StorageClasses.o

# target to build an object file
src/storageclasses/StorageClasses.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/storageclasses/StorageClasses.cpp.o
.PHONY : src/storageclasses/StorageClasses.cpp.o

src/storageclasses/StorageClasses.i: src/storageclasses/StorageClasses.cpp.i
.PHONY : src/storageclasses/StorageClasses.i

# target to preprocess a source file
src/storageclasses/StorageClasses.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/storageclasses/StorageClasses.cpp.i
.PHONY : src/storageclasses/StorageClasses.cpp.i

src/storageclasses/StorageClasses.s: src/storageclasses/StorageClasses.cpp.s
.PHONY : src/storageclasses/StorageClasses.s

# target to generate assembly for a file
src/storageclasses/StorageClasses.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/learning_cpp.dir/build.make CMakeFiles/learning_cpp.dir/src/storageclasses/StorageClasses.cpp.s
.PHONY : src/storageclasses/StorageClasses.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... learning_cpp"
	@echo "... src/0-helloworld/HelloWorld.o"
	@echo "... src/0-helloworld/HelloWorld.i"
	@echo "... src/0-helloworld/HelloWorld.s"
	@echo "... src/1-datatypes/DataTypes.o"
	@echo "... src/1-datatypes/DataTypes.i"
	@echo "... src/1-datatypes/DataTypes.s"
	@echo "... src/2-controlflows/ControlFlows.o"
	@echo "... src/2-controlflows/ControlFlows.i"
	@echo "... src/2-controlflows/ControlFlows.s"
	@echo "... src/3-functions/Functions.o"
	@echo "... src/3-functions/Functions.i"
	@echo "... src/3-functions/Functions.s"
	@echo "... src/4-modifiertypes/ModifierTypes.o"
	@echo "... src/4-modifiertypes/ModifierTypes.i"
	@echo "... src/4-modifiertypes/ModifierTypes.s"
	@echo "... src/5-numbers/Numbers.o"
	@echo "... src/5-numbers/Numbers.i"
	@echo "... src/5-numbers/Numbers.s"
	@echo "... src/6-arrays/Arrays.o"
	@echo "... src/6-arrays/Arrays.i"
	@echo "... src/6-arrays/Arrays.s"
	@echo "... src/7-strings/Strings.o"
	@echo "... src/7-strings/Strings.i"
	@echo "... src/7-strings/Strings.s"
	@echo "... src/8-datetime/DateTime.o"
	@echo "... src/8-datetime/DateTime.i"
	@echo "... src/8-datetime/DateTime.s"
	@echo "... src/9-operators/Operators.o"
	@echo "... src/9-operators/Operators.i"
	@echo "... src/9-operators/Operators.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/pointers/Pointers.o"
	@echo "... src/pointers/Pointers.i"
	@echo "... src/pointers/Pointers.s"
	@echo "... src/storageclasses/StorageClasses.o"
	@echo "... src/storageclasses/StorageClasses.i"
	@echo "... src/storageclasses/StorageClasses.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

